### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by Mr-CYBERPAPER** [mustafaquraish/cup#7]
First of all, i wanna thank you for this repo :)
This is not a issue, but a question, since obviously you have more experience than me, and im just trying to find something....
 I was searching for more repos like this, a kind of "programming language", but i literally found nothing, if you had to know some code that could help i will be thankful. !
I basically would love to have it in c/cpp, but anything can work !

Thanks for your time, and hope you reply soon :)

**Comment by mustafaquraish** [comment]
The initial implementation for the language was in C, if you look at the git history, you can find it [here](https://github.com/mustafaquraish/cup/tree/e5f2fac8c5ae5a1b74335816836872c2e24904e6) (in the `src` folder).
